version: "3.8"

services:
  api:
    build: ../backend
    container_name: orbit_api
    restart: always
    ports:
      - "4000:4000"
    environment:
      DATABASE_URL: ${DATABASE_URL}
      REDIS_URL: ${REDIS_URL}
      PORT: 4000
    depends_on:
      - db
      - redis

  db:
    image: postgres:15
    container_name: orbit_db
    restart: always
    environment:
      POSTGRES_DB: orbitdb
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

  redis:
    image: redis:latest
    container_name: orbit_redis
    restart: always
    ports:
      - "6379:6379"

volumes:
  pgdata:
