name: Backend Test and Build

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    name: Run Backend Tests
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: apps/backend

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install dependencies
        run: |
          pip install -r requirements.txt

      - name: Run unit tests
        run: |
          python -m unittest discover -s tests -v
          
  build:
    name: Build Backend Docker Image
    runs-on: ubuntu-latest
    needs: test

    defaults:
      run:
        working-directory: apps/backend

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Build Docker image
        run: |
          docker build -t backend:latest .

      # Optional: Push to Docker Hub (if you later want)
      # - name: Log in to Docker Hub
      #   run: echo "${{ secrets.DOCKERHUB_TOKEN }}" | docker login -u "${{ secrets.DOCKERHUB_USERNAME }}" --password-stdin
      #
      # - name: Push image
      #   run: |
      #     docker tag backend:latest myusername/backend:latest
      #     docker push myusername/backend:latest