name: Deploy Backend

on:
  push:
    branches: [ main ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v3
    
    - name: Set up SSH
      uses: webfactory/ssh-agent@v0.7.0
      with:
        ssh-private-key: ${{ secrets.EC2_SSH_KEY }}

    - name: Copy cloud folder to EC2
      run: scp -o StrictHostKeyChecking=no -r cloud-development ubuntu@${{ secrets.EC2_HOST }}:~/cloud-project

    - name: Run deploy script
      run: ssh -o StrictHostKeyChecking=no ubuntu@${{ secrets.EC2_HOST }} "cd cloud-project && bash deploy.sh"
